## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  
  - docker tag udagram-api-feed sonic3k/udagram-api-feed:v1
  - docker tag udagram-api-user sonic3k/udagram-api-user:v1
  - docker tag udagram-frontend sonic3k/udagram-frontend:v1
  - docker tag udagram-reverseproxy sonic3k/udagram-reverseproxy:v1
  
  ```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sonic3k/udagram-api-feed:v1
  - docker push sonic3k/udagram-api-user:v1
  - docker push sonic3k/udagram-frontend:v1
  - docker push sonic3k/reverseproxy:v1

