version: 2.1

orbs:
  node: circleci/node@5.0.2  # Latest stable version of Node Orb

jobs:
  build_and_push:
    docker:
      - image: cimg/node:14.19.0  
    steps:
      - checkout 
      - node/install-packages:
          override-ci-command: npm ci 
      - run: 
          name: Build Images
          command: | 
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - run:
          name: Tag Images
          command: |
            docker tag udagram-api-feed sonic3k/udagram-api-feed:v1
            docker tag udagram-api-user sonic3k/udagram-api-user:v1
            docker tag udagram-frontend sonic3k/udagram-frontend:v1
            docker tag udagram-reverseproxy sonic3k/udagram-reverseproxy:v1

      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Push Images
          command: |
            docker push sonic3k/udagram-api-feed:v1
            docker push sonic3k/udagram-api-user:v1
            docker push sonic3k/udagram-frontend:v1
            docker push sonic3k/udagram-reverseproxy:v1 

workflows:
  build_and_push_workflow:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main 
