version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_push:
    docker:
      - image: cimg/node:14.19.0
    working_directory: ~/project 

    steps:
      - checkout 
      
      # Install Dependencies for Each Service
      - node/install-packages:
          app-dir: ./udagram-api-feed  
          override-ci-command: npm ci || exit 1
      - node/install-packages:
          app-dir: ./udagram-api-user 
          override-ci-command: npm ci || exit 1
      - node/install-packages:
          app-dir: ./udagram-frontend 
          override-ci-command: npm ci || exit 1
      - node/install-packages:
          app-dir: ./udagram-reverseproxy 
          override-ci-command: npm ci || exit 1
      
      # Build Docker Images (with error handling)
      - run: 
          name: Build Images
          command: | 
            docker build -t udagram-api-feed ./udagram-api-feed || exit 1
            docker build -t udagram-api-user ./udagram-api-user || exit 1
            docker build -t udagram-frontend ./udagram-frontend || exit 1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy || exit 1

      - run:
          name: Tag Images
          command: |
            docker tag udagram-api-feed sonic3k/udagram-api-feed:v1
            docker tag udagram-api-user sonic3k/udagram-api-user:v1
            docker tag udagram-frontend sonic3k/udagram-frontend:v1
            docker tag udagram-reverseproxy sonic3k/udagram-reverseproxy:v1

      # Docker Login (using environment variables)
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Push Images
          command: |
            docker push sonic3k/udagram-api-feed:v1 || exit 1
            docker push sonic3k/udagram-api-user:v1 || exit 1
            docker push sonic3k/udagram-frontend:v1 || exit 1
            docker push sonic3k/udagram-reverseproxy:v1 || exit 1


workflows:
  build_and_push_workflow:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main # Trigger the workflow only for pushes to the 'main' branch
